<div dir="rtl">

# فصل ۳: دستکاری داده‌های جدولی با استفاده از Pandas

## Pandas چیست؟

در حالی که آرایه‌های NumPy نسخه‌ای بسیار بهبود یافته از شیء آرایه N بعدی نسبت به لیست پایتون هستند، برای پاسخگویی به نیازهای علم داده کافی نیستند. در دنیای واقعی، داده‌ها اغلب در قالب‌های جدولی ارائه می‌شوند. به عنوان مثال، محتوای فایل CSV نشان داده شده در زیر را در نظر بگیرید:

</div>

In [64]:
# محتوای نمونه فایل CSV
# ,DateTime,mmol/L
# 0,2016-06-01 08:00:00,6.1
# 1,2016-06-01 12:00:00,6.5
# 2,2016-06-01 18:00:00,6.7
# ...

<div dir="rtl">

فایل CSV شامل ردیف‌هایی از داده است که به سه ستون تقسیم شده‌اند - ایندکس، تاریخ و زمان ثبت، و مقادیر گلوکز خون بر حسب mmol/L. برای اینکه بتوانیم با داده‌های ذخیره شده به صورت جداول کار کنیم، به یک نوع داده جدید نیاز داریم که مناسب‌تر برای کار با آن باشد - Pandas. در حالی که پایتون از لیست‌ها و دیکشنری‌ها برای دستکاری داده‌های ساختاریافته پشتیبانی می‌کند، دستکاری جداول عددی، مانند جدول ذخیره شده در فایل CSV، مناسب نیست. Pandas یک بسته پایتون است که ساختارهای داده سریع، انعطاف‌پذیر و بیانی را ارائه می‌دهد که برای کار با داده‌های "رابطه ای" یا "برچسب‌دار" هم آسان و هم شهودی طراحی شده‌اند.

**نکته:** Pandas مخفف Panel Data Analysis است.

Pandas از دو ساختار داده کلیدی پشتیبانی می‌کند: Series و DataFrame. در این فصل، نحوه کار با Series و DataFrames در Pandas را یاد خواهید گرفت.

---

## Pandas Series

یک Series در Pandas یک آرایه یک‌بعدی شبیه NumPy است، که هر عنصر دارای یک ایندکس (به طور پیش‌فرض 0، 1، 2، ...) است؛ یک Series بسیار شبیه به یک دیکشنری رفتار می‌کند که شامل یک ایندکس است.

برای ایجاد یک Series، ابتدا باید کتابخانه pandas را وارد کنید (قرارداد استفاده از `pd` به عنوان نام مستعار است) و سپس از کلاس `Series` استفاده کنید:

</div>

In [65]:
import pandas as pd
series = pd.Series(['1',2,3,4,5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: object

In [66]:
print(type(series))

<class 'pandas.Series'>

<div dir="rtl">

به طور پیش‌فرض، ایندکس یک Series از 0 شروع می‌شود.

### ایجاد یک Series با استفاده از ایندکس مشخص

می‌توانید یک ایندکس اختیاری برای یک Series با استفاده از پارامتر `index` مشخص کنید:

</div>

In [67]:
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])  # توجه: ایندکس تکراری 'c'
print(series)

a    1
b    2
c    3
d    4
c    5
dtype: int64

<div dir="rtl">

قابل توجه است که ایندکس یک Series لزومی ندارد یکتا باشد، همانطور که خروجی بالا نشان می‌دهد.

### دسترسی به عناصر در یک Series

دسترسی به یک عنصر در Series مشابه دسترسی به یک عنصر در آرایه است. می‌توانید از موقعیت عنصر به صورت زیر استفاده کنید:

</div>

In [68]:
print(series['c'])

c    3
c    5
dtype: int64

In [69]:
          # 3
# معادل
print(series.iloc[2])     # 3 - بر اساس موقعیت ایندکس

3

In [70]:
print(series.loc['c'])

c    3
c    5
dtype: int64

<div dir="rtl">

ایندکسر `iloc` به شما امکان می‌دهد یک عنصر را از طریق موقعیت آن مشخص کنید.

همچنین می‌توانید مقدار ایندکس عنصری را که می‌خواهید به آن دسترسی پیدا کنید به این صورت مشخص کنید:

</div>

In [71]:
print(series['d'])        # 4
# معادل
print(series.loc['d'])    # 4 - بر اساس برچسب در ایندکس

4
4

<div dir="rtl">

ایندکسر `loc` به شما امکان می‌دهد برچسب (مقدار) یک ایندکس را مشخص کنید.

توجه داشته باشید که در دو مثال بالا، نتیجه یک عدد صحیح است (که نوع این Series است). اگر کار زیر را انجام دهیم چه اتفاقی می‌افتد؟

</div>

In [72]:
print(series['c'])        # بیش از یک سطر ایندکس 'c' را دارند

c    3
c    5
dtype: int64

In [73]:
print(series['d'])
print(type(series['c']))
print(type(series['d']))

4
<class 'pandas.Series'>
<class 'numpy.int64'>

In [74]:
print(type(series['c']))

<class 'pandas.Series'>

<div dir="rtl">

در این حالت، نتیجه یک Series دیگر خواهد بود.

همچنین می‌توانید برش را روی یک Series انجام دهید:

</div>

In [75]:
print(series[2:])         # یک Series برمی‌گرداند
print(series.iloc[2:])    # یک Series برمی‌گرداند

c    3
d    4
c    5
dtype: int64
c    3
d    4
c    5
dtype: int64

<div dir="rtl">

### مشخص کردن یک محدوده تاریخ و زمان به عنوان ایندکس یک Series

اغلب، می‌خواهید یک سری زمانی ایجاد کنید، مانند یک دنباله در حال اجرا از تاریخ‌ها در یک ماه. می‌توانید از تابع `date_range()` برای این منظور استفاده کنید:

</div>

In [76]:
dates1 = pd.date_range('20190525', periods=12)
print(dates1)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[us]', freq='D')

<div dir="rtl">

برای اختصاص محدوده تاریخ‌ها به عنوان ایندکس یک Series، از ویژگی `index` Series به این صورت استفاده کنید:

</div>

In [77]:
series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
series.index = dates1
print(series)

2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64

<div dir="rtl">

## محدوده‌های تاریخ (Date Ranges)

در بخش قبل، دیدید که چگونه می‌توان با استفاده از تابع `date_range()` محدوده‌های تاریخ ایجاد کرد. پارامتر `periods` مشخص می‌کند که چند تاریخ می‌خواهید ایجاد کنید، و فرکانس پیش‌فرض `D` (برای روزانه) است. اگر می‌خواهید فرکانس را به ماه تغییر دهید، از پارامتر `freq` استفاده کنید و آن را روی `ME` تنظیم کنید:

</div>

In [78]:
dates2 = pd.date_range('2019-05-01', periods=12, freq='ME')
print(dates2)

DatetimeIndex(['2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31',
               '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30'],
              dtype='datetime64[us]', freq='ME')

<div dir="rtl">

توجه کنید که وقتی فرکانس روی ماه تنظیم می‌شود، روز هر تاریخ آخرین روز ماه خواهد بود. اگر می‌خواهید تاریخ با اولین روز ماه شروع شود، پارامتر `freq` را روی `MS` تنظیم کنید:

</div>

In [79]:
dates2 = pd.date_range('2019-05-01', periods=12, freq='MS')
print(dates2)

DatetimeIndex(['2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01',
               '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01',
               '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01'],
              dtype='datetime64[us]', freq='MS')

<div dir="rtl">

توجه کنید که Pandas به طور خودکار تاریخ مشخص شده را تفسیر می‌کند. در این مورد، `2019-05-01` به عنوان ۱ مه ۲۰۱۹ تفسیر می‌شود. در برخی مناطق، توسعه‌دهندگان تاریخ را در قالب `dd-mm-yyyy` مشخص می‌کنند. بنابراین برای نمایش ۵ ژانویه ۲۰۱۹، آن را به صورت زیر مشخص می‌کنید:

</div>

In [80]:
dates2 = pd.date_range('05-01-2019', periods=12, freq='MS')
print(dates2)

DatetimeIndex(['2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01',
               '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01',
               '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01'],
              dtype='datetime64[us]', freq='MS')

<div dir="rtl">

علاوه بر تنظیم تاریخ‌ها، می‌توانید زمان را نیز تنظیم کنید:

</div>

In [81]:
dates3 = pd.date_range('2019/05/17 09:00:00', periods=8, freq='h')
print(dates3)

DatetimeIndex(['2019-05-17 09:00:00', '2019-05-17 10:00:00',
               '2019-05-17 11:00:00', '2019-05-17 12:00:00',
               '2019-05-17 13:00:00', '2019-05-17 14:00:00',
               '2019-05-17 15:00:00', '2019-05-17 16:00:00'],
              dtype='datetime64[us]', freq='h')

<div dir="rtl">

**نکته:** اگر هر یک از قطعه کدهایی را که در این بخش دیده‌اید مرور کنید، خواهید دید که Pandas به شما امکان می‌دهد تاریخ را در قالب‌های مختلفی مانند `mm-dd-yyyy`، `yyyy-mm-dd` و `yyyy/mm/dd` مشخص کنید، و به طور خودکار سعی می‌کند تاریخ‌های مشخص شده را تفسیر کند. هنگامی که شک دارید، همیشه مفید است که محدوده تاریخ‌ها را چاپ کنید تا تأیید شود.

---

# Pandas DataFrame

یک DataFrame در Pandas یک آرایه دو بعدی شبیه NumPy است. می‌توانید آن را به عنوان یک جدول در نظر بگیرید.

یک DataFrame در دنیای علم داده و یادگیری ماشین بسیار مفید است، زیرا بازتاب نزدیکی از نحوه ذخیره‌سازی داده‌ها در زندگی واقعی دارد. داده‌های ذخیره شده در یک صفحه گسترده را تصور کنید، و تصویر بصری بسیار خوبی از یک DataFrame خواهید داشت. یک DataFrame در Pandas اغلب هنگام نمایش داده‌ها در یادگیری ماشین استفاده می‌شود. بنابراین، برای بخش‌های باقی‌مانده در این فصل، زمان و تلاش قابل توجهی را صرف درک نحوه کار آن خواهیم کرد.

## ایجاد یک DataFrame

می‌توانید یک DataFrame در Pandas را با استفاده از کلاس `DataFrame()` ایجاد کنید:

</div>

In [167]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10,4),
                  columns=['A','B','C','D'])
print(df)

          A         B         C         D
0 -0.181516  1.856964  0.402379 -0.521415
1 -0.809621  0.776567 -0.464975 -0.039026
2  0.853382  0.231739 -0.516556  2.212415
3  0.423137  0.896598 -0.336582 -0.891392
4  1.794649  0.234149 -1.846714  1.363579
5 -1.064663 -0.869951  0.270242 -0.687024
6 -0.381792  0.419996  1.972837  0.102781
7 -1.028494  0.707884  0.298527  0.467032
8 -0.564868 -0.024645 -0.204662 -0.843438
9 -0.642729  0.591121 -0.243195  0.159419

<div dir="rtl">

در قطعه کد بالا، یک DataFrame از ۱۰ سطر و ۴ ستون ایجاد شد، و هر خانه با یک عدد تصادفی با استفاده از تابع `randn()` پر شده است. هر ستون یک برچسب دارد: "A"، "B"، "C" و "D".

**نکته:** بدیهی است که شما مجموعه اعداد متفاوتی را در DataFrame خود خواهید دید، زیرا اعداد به صورت تصادفی تولید می‌شوند.

اغلب اوقات، یک DataFrame معمولاً از یک فایل متنی، مانند یک فایل CSV، بارگذاری می‌شود. فرض کنید یک فایل CSV به نام `data.csv` با محتوای زیر دارید:

</div>

In [83]:
# محتوای فایل data.csv
# A,B,C,D
# 0.187497,1.122150,-0.988277,-1.985934
# 0.360803,-0.562243,-0.340693,-0.986988
# -0.040627,0.067333,-0.452978,0.686223
# -0.279572,-0.702492,0.252265,0.958977
# 0.537438,-1.737568,0.714727,-0.939288
# 0.070011,-0.516443,-1.655689,0.246721
# 0.001268,0.951517,2.107360,-0.108726
# -0.185258,0.856520,-0.686285,1.104195
# 0.387023,1.706336,-2.452653,0.260466
# -1.054974,0.556775,-0.945219,-0.030295

<div dir="rtl">

می‌توانید محتوای فایل CSV را با استفاده از تابع `read_csv()` در یک DataFrame بارگذاری کنید:

</div>

In [84]:
df = pd.read_csv('data.csv')               # بارگذاری dataframe از فایل CSV
days = pd.date_range('20190525', periods=10)
df.index = days
print(df)

                   A         B         C         D
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-28 -0.279572 -0.702492  0.252265  0.958977
2019-05-29  0.537438 -1.737568  0.714727 -0.939288
2019-05-30  0.070011 -0.516443 -1.655689  0.246721
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

## مشخص کردن ایندکس در یک DataFrame

توجه کنید که DataFrame چاپ شده در بخش قبل دارای یک ایندکس است که از 0 شروع می‌شود. این شبیه به یک Series است. مانند یک Series، می‌توانید ایندکس را برای DataFrame با استفاده از ویژگی `index` تنظیم کنید.

برای دریافت ایندکس DataFrame، از ویژگی `index` به صورت زیر استفاده کنید:

</div>

In [85]:
print(df.index)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03'],
              dtype='datetime64[us]', freq='D')

<div dir="rtl">

اگر می‌خواهید مقادیر کل DataFrame را به عنوان یک ndarray دو بعدی دریافت کنید، از ویژگی `values` استفاده کنید:

</div>

In [86]:
print(df.values)
print(type(df.values))
print(df.values.shape)

[[ 1.874970e-01  1.122150e+00 -9.882770e-01 -1.985934e+00]
 [ 3.608030e-01 -5.622430e-01 -3.406930e-01 -9.869880e-01]
 [-4.062700e-02  6.733300e-02 -4.529780e-01  6.862230e-01]
 [-2.795720e-01 -7.024920e-01  2.522650e-01  9.589770e-01]
 [ 5.374380e-01 -1.737568e+00  7.147270e-01 -9.392880e-01]
 [ 7.001100e-02 -5.164430e-01 -1.655689e+00  2.467210e-01]
 [ 1.268000e-03  9.515170e-01  2.107360e+00 -1.087260e-01]
 [-1.852580e-01  8.565200e-01 -6.862850e-01  1.104195e+00]
 [ 3.870230e-01  1.706336e+00 -2.452653e+00  2.604660e-01]
 [-1.054974e+00  5.567750e-01 -9.452190e-01 -3.029500e-02]]
<class 'numpy.ndarray'>
(10, 4)

<div dir="rtl">

## تولید آمار توصیفی روی DataFrame

DataFrame در Pandas با چند تابع مفید برای ارائه آمار دقیق در مورد مقادیر موجود در DataFrame ارائه می‌شود. به عنوان مثال، می‌توانید از تابع `describe()` برای دریافت مقادیری مانند تعداد، میانگین، انحراف معیار، حداقل و حداکثر، و همچنین چارک‌های مختلف استفاده کنید:

</div>

In [87]:
print(df.describe())

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.001639   0.174188  -0.444744  -0.079465
std     0.451656   1.049677   1.267397   0.971164
min    -1.054974  -1.737568  -2.452653  -1.985934
25%    -0.149100  -0.550793  -0.977513  -0.731648
50%     0.035640   0.312054  -0.569632   0.108213
75%     0.317476   0.927768   0.104025   0.579784
max     0.537438   1.706336   2.107360   1.104195

<div dir="rtl">

اگر فقط می‌خواهید میانگین را در DataFrame محاسبه کنید، می‌توانید از تابع `mean()` استفاده کنید و محور را مشخص کنید:

</div>

In [88]:
print(df.mean(0))    # 0 یعنی محاسبه میانگین برای هر ستون

A   -0.001639
B    0.174188
C   -0.444744
D   -0.079465
dtype: float64

C:\Users\thinkbook\AppData\Local\Temp\ipykernel_17784\1531835795.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  print(df.mean(0))    # 0 یعنی محاسبه میانگین برای هر ستون

<div dir="rtl">

اگر می‌خواهید میانگین هر سطر را دریافت کنید، محور را روی 1 تنظیم کنید:

</div>

In [89]:
print(df.mean(1))   # 1 یعنی محاسبه میانگین برای هر سطر

2019-05-25   -0.416141
2019-05-26   -0.382280
2019-05-27    0.064988
2019-05-28    0.057294
2019-05-29   -0.356173
2019-05-30   -0.463850
2019-05-31    0.737855
2019-06-01    0.272293
2019-06-02   -0.024707
2019-06-03   -0.368428
Freq: D, dtype: float64

C:\Users\thinkbook\AppData\Local\Temp\ipykernel_17784\3407370056.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  print(df.mean(1))   # 1 یعنی محاسبه میانگین برای هر سطر

<div dir="rtl">

## استخراج از DataFrames

در فصل ۲، "گسترش پایتون با استفاده از NumPy"، با NumPy و نحوه برش برای استخراج بخشی از یک آرایه NumPy آشنا شدید. به همین ترتیب، در Pandas، برش هم برای Series و هم برای DataFrames اعمال می‌شود.

از آنجا که استخراج سطرها و ستون‌ها در DataFrames یکی از رایج‌ترین کارهایی است که با DataFrames انجام خواهید داد (و احتمالاً می‌تواند گیج‌کننده باشد)، بیایید روش‌های مختلف را گام به گام مرور کنیم تا زمان کافی برای درک نحوه کار آنها داشته باشید.

### انتخاب پنج سطر اول و آخر

گاهی اوقات، DataFrame ممکن است بیش از حد طولانی باشد، و شما فقط می‌خواهید نگاهی به چند سطر اول در DataFrame بیندازید. برای این منظور، می‌توانید از تابع `head()` استفاده کنید:

</div>

In [90]:
print(df.head())

                   A         B         C         D
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-28 -0.279572 -0.702492  0.252265  0.958977
2019-05-29  0.537438 -1.737568  0.714727 -0.939288

<div dir="rtl">

اگر بیش از پنج سطر (یا کمتر از پنج) می‌خواهید، می‌توانید تعداد سطرهای مورد نظر را در تابع `head()` به صورت زیر مشخص کنید:

</div>

In [91]:
print(df.head(2))     # چاپ 8 سطر اول

                   A         B         C         D
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988

<div dir="rtl">

همچنین یک تابع `tail()` وجود دارد:

</div>

In [92]:
print(df.tail())

                   A         B         C         D
2019-05-30  0.070011 -0.516443 -1.655689  0.246721
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

مانند تابع `head()`، تابع `tail()` به شما امکان می‌دهد تعداد سطرهایی را که باید چاپ شوند مشخص کنید:

</div>

In [93]:
print(df.tail(3))     # چاپ 8 سطر آخر

                   A         B         C         D
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

### انتخاب یک ستون خاص در DataFrame

برای به دست آوردن یک یا چند ستون در DataFrame، می‌توانید برچسب ستون را به صورت زیر مشخص کنید:

</div>

In [94]:
print(df['A'])
# معادل
print(df.A)
print(type(df.A))

2019-05-25    0.187497
2019-05-26    0.360803
2019-05-27   -0.040627
2019-05-28   -0.279572
2019-05-29    0.537438
2019-05-30    0.070011
2019-05-31    0.001268
2019-06-01   -0.185258
2019-06-02    0.387023
2019-06-03   -1.054974
Freq: D, Name: A, dtype: float64
2019-05-25    0.187497
2019-05-26    0.360803
2019-05-27   -0.040627
2019-05-28   -0.279572
2019-05-29    0.537438
2019-05-30    0.070011
2019-05-31    0.001268
2019-06-01   -0.185258
2019-06-02    0.387023
2019-06-03   -1.054974
Freq: D, Name: A, dtype: float64
<class 'pandas.Series'>

<div dir="rtl">

این دستور ستون "A" را همراه با ایندکس آن چاپ می‌کند. در اصل، چیزی که در عوض دریافت می‌کنید یک Series است. اگر می‌خواهید بیش از یک ستون را بازیابی کنید، یک لیست حاوی برچسب‌های ستون را وارد کنید:

</div>

In [95]:
print(df[['A', 'B']])

                   A         B
2019-05-25  0.187497  1.122150
2019-05-26  0.360803 -0.562243
2019-05-27 -0.040627  0.067333
2019-05-28 -0.279572 -0.702492
2019-05-29  0.537438 -1.737568
2019-05-30  0.070011 -0.516443
2019-05-31  0.001268  0.951517
2019-06-01 -0.185258  0.856520
2019-06-02  0.387023  1.706336
2019-06-03 -1.054974  0.556775

In [96]:
print(type(df[['A','B']]))

<class 'pandas.DataFrame'>

<div dir="rtl">

در این مورد، به جای یک Series، اکنون یک DataFrame دریافت می‌کنید.

### برش بر اساس شماره سطر

ابتدا، بیایید یک محدوده از سطرها را در DataFrame استخراج کنیم:

</div>

In [97]:
print(df[2:4])

                   A         B         C         D
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-28 -0.279572 -0.702492  0.252265  0.958977

<div dir="rtl">

این دستور شماره سطرهای ۲ تا ۴ (شامل سطر ۲، غیر شامل سطر ۴) را از DataFrame استخراج می‌کند.

همچنین می‌توانید از ایندکسر `iloc` برای استخراج سطرها بر اساس شماره سطر استفاده کنید:

</div>

In [98]:
print(df.iloc[2:4])      # 2 سطر

                   A         B         C         D
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-28 -0.279572 -0.702492  0.252265  0.958977

<div dir="rtl">

توجه داشته باشید که اگر می‌خواهید سطرهای خاصی (و نه یک محدوده از سطرها) را با استفاده از شماره سطر استخراج کنید، باید از ایندکسر `iloc` به این صورت استفاده کنید:

</div>

In [99]:
print(df.iloc[[2,4,7]])    # 2 سطر

                   A         B         C         D
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-29  0.537438 -1.737568  0.714727 -0.939288
2019-06-01 -0.185258  0.856520 -0.686285  1.104195

<div dir="rtl">

بدون استفاده از ایندکسر `iloc`، دستور زیر کار نخواهد کرد:

</div>

In [100]:
# print(df[[2,4]])   # خطا؛ باید از ایندکسر iloc استفاده کنید
print(df.iloc[2])    # چاپ سطر شماره 2

A   -0.040627
B    0.067333
C   -0.452978
D    0.686223
Name: 2019-05-27 00:00:00, dtype: float64

<div dir="rtl">

### برش بر اساس شماره سطر و ستون

اگر می‌خواهید سطرها و ستون‌های خاصی را در یک DataFrame استخراج کنید، باید از ایندکسر `iloc` استفاده کنید. قطعه کد زیر شماره سطرهای ۲ تا ۳ و شماره ستون‌های ۱ تا ۳ را استخراج می‌کند:

</div>

In [101]:
print(df.iloc[2:4, 1:4])        # 2 سطر، 3 ستون

                   B         C         D
2019-05-27  0.067333 -0.452978  0.686223
2019-05-28 -0.702492  0.252265  0.958977

<div dir="rtl">

همچنین می‌توانید سطرها و ستون‌های خاصی را با استفاده از یک لیست به صورت زیر استخراج کنید:

</div>

In [102]:
print(df.iloc[[2,4], [1,3]])    # 2 سطر، 2 ستون

                   B         D
2019-05-27  0.067333  0.686223
2019-05-29 -1.737568 -0.939288

<div dir="rtl">

**نکته:** برای خلاصه، اگر می‌خواهید یک محدوده از سطرها را با استفاده از برش استخراج کنید، می‌توانید به سادگی از نحو زیر استفاده کنید: `df[start_row:end_row]`. اگر می‌خواهید سطرها یا ستون‌های خاصی را استخراج کنید، از ایندکسر `iloc` استفاده کنید: `df.iloc[[row_1, row_2, ..., row_n], [column_1, column_2, ..., column_n]]`.

### برش بر اساس برچسب‌ها

علاوه بر استخراج سطرها و ستون‌ها با استفاده از شماره سطر و ستون، می‌توانید آنها را با برچسب (مقدار) نیز استخراج کنید. به عنوان مثال، قطعه کد زیر یک محدوده از سطرها را با استفاده از مقادیر ایندکس آنها (که از نوع DatetimeIndex است) استخراج می‌کند:

</div>

In [103]:
print(df['20190601':'20190603'])

                   A         B         C         D
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

همچنین می‌توانید از ایندکسر `loc` به صورت زیر استفاده کنید:

</div>

In [104]:
print(df.loc['20190601':'20190603'])

                   A         B         C         D
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

استفاده از ایندکسر `loc` اگر می‌خواهید ستون‌ها را با استفاده از مقادیر آنها استخراج کنید، الزامی است، همانطور که مثال زیر نشان می‌دهد:

</div>

In [105]:
print(df.loc['20190601':'20190603', 'A':'C'])

                   A         B         C
2019-06-01 -0.185258  0.856520 -0.686285
2019-06-02  0.387023  1.706336 -2.452653
2019-06-03 -1.054974  0.556775 -0.945219

<div dir="rtl">

**نکته:** برخلاف برش با شماره، که در آن `start:end` به معنای استخراج سطرهای start تا end است اما end را شامل نمی‌شود، برش با مقدار، سطر end را نیز شامل می‌شود.

همچنین می‌توانید ستون‌های خاصی را استخراج کنید:

</div>

In [106]:
print(df.loc['20190601':'20190603', ['A','C']])

                   A         C
2019-06-01 -0.185258 -0.686285
2019-06-02  0.387023 -2.452653
2019-06-03 -1.054974 -0.945219

<div dir="rtl">

اگر می‌خواهید یک سطر خاص را استخراج کنید، از ایندکسر `loc` به صورت زیر استفاده کنید:

</div>

In [107]:
print(df.loc['20190601'])

A   -0.185258
B    0.856520
C   -0.686285
D    1.104195
Name: 2019-06-01 00:00:00, dtype: float64

<div dir="rtl">

به طور عجیب، اگر می‌خواهید سطرهای خاصی را با datetime به عنوان ایندکس استخراج کنید، نمی‌توانید به سادگی مقدار تاریخ را به ایندکسر `loc` به صورت زیر ارسال کنید:

</div>

In [108]:
print(df.loc[['20190601','20190603'],['A','C']])   # KeyError

                   A         C
2019-06-01 -0.185258 -0.686285
2019-06-03 -1.054974 -0.945219

In [109]:
print(df.loc[['20190601'],'A'])

2019-06-01   -0.185258
Name: A, dtype: float64

<div dir="rtl">

ابتدا، باید تاریخ را به فرمت datetime تبدیل کنید:

</div>

In [110]:
from datetime import datetime
date1 = datetime(2019, 6, 1, 0, 0, 0)
date2 = datetime(2019, 6, 3, 0, 0, 0)
print(df.loc[[date1,date2]])

                   A         B         C         D
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295

<div dir="rtl">

**نکته:** برای خلاصه، اگر می‌خواهید یک محدوده از سطرها را با استفاده از برچسب‌های آنها استخراج کنید، می‌توانید به سادگی از نحو زیر استفاده کنید: `df[start_label:end_label]`. 
اگر می‌خواهید سطرها یا ستون‌های خاصی را استخراج کنید، از ایندکسر `loc` با نحو زیر استفاده کنید: `df.loc[[row_1_label, row_2_label, ..., row_n_label], [column_1_label, column_2_label, ..., column_n_label]]`.

</div>

<div dir="rtl">

## انتخاب بر اساس مقدار سلول

اگر می‌خواهید یک زیرمجموعه از DataFrame را بر اساس مقادیر خاصی در سلول‌ها انتخاب کنید، می‌توانید از روش نمایه‌گذاری بولی استفاده کنید، همانطور که در فصل ۲ توضیح داده شد. قطعه کد زیر تمام سطرهایی را که مقادیر مثبت در ستون‌های A و B دارند چاپ می‌کند:

</div>

In [111]:
print(df[(df.A > 0) & (df.B > 0)])

                   A         B         C         D
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-06-02  0.387023  1.706336 -2.452653  0.260466

<div dir="rtl">

## تبدیل DataFrames

اگر نیاز دارید DataFrame را نسبت به قطر اصلی آن منعکس کنید (تبدیل ستون‌ها به سطرها و سطرها به ستون‌ها)، می‌توانید از تابع `transpose()` استفاده کنید:

</div>

In [112]:
print(df.transpose())

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.187497    0.360803   -0.040627   -0.279572    0.537438    0.070011
B    1.122150   -0.562243    0.067333   -0.702492   -1.737568   -0.516443
C   -0.988277   -0.340693   -0.452978    0.252265    0.714727   -1.655689
D   -1.985934   -0.986988    0.686223    0.958977   -0.939288    0.246721

   2019-05-31  2019-06-01  2019-06-02  2019-06-03
A    0.001268   -0.185258    0.387023   -1.054974
B    0.951517    0.856520    1.706336    0.556775
C    2.107360   -0.686285   -2.452653   -0.945219
D   -0.108726    1.104195    0.260466   -0.030295

<div dir="rtl">

یا می‌توانید فقط از ویژگی `T` استفاده کنید، که یک دسترسی‌دهنده به تابع `transpose()` است:

</div>

In [113]:
print(df.T)

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.187497    0.360803   -0.040627   -0.279572    0.537438    0.070011
B    1.122150   -0.562243    0.067333   -0.702492   -1.737568   -0.516443
C   -0.988277   -0.340693   -0.452978    0.252265    0.714727   -1.655689
D   -1.985934   -0.986988    0.686223    0.958977   -0.939288    0.246721

   2019-05-31  2019-06-01  2019-06-02  2019-06-03
A    0.001268   -0.185258    0.387023   -1.054974
B    0.951517    0.856520    1.706336    0.556775
C    2.107360   -0.686285   -2.452653   -0.945219
D   -0.108726    1.104195    0.260466   -0.030295

<div dir="rtl">

## بررسی اینکه آیا یک نتیجه DataFrame است یا Series

یکی از مشکلات رایجی که با Pandas مواجه خواهید شد، دانستن این است که نتیجه‌ای که به دست آورده‌اید یک Series است یا DataFrame. برای حل این معما، در اینجا تابعی وجود دارد که می‌تواند کار شما را آسان‌تر کند:

</div>

In [114]:
def checkSeriesOrDataframe(var):
    if isinstance(var, pd.DataFrame):
        return 'Dataframe'
    if isinstance(var, pd.Series):
        return 'Series'

In [115]:
checkSeriesOrDataframe(df)

'Dataframe'

In [116]:
df1 = df['A']
checkSeriesOrDataframe(df1)

'Series'

<div dir="rtl">

## مرتب‌سازی داده‌ها در یک DataFrame

دو راه برای مرتب‌سازی داده‌ها در یک DataFrame وجود دارد:

1. مرتب‌سازی بر اساس برچسب‌ها (محور) با استفاده از تابع `sort_index()`
2. مرتب‌سازی بر اساس مقدار با استفاده از تابع `sort_values()`

### مرتب‌سازی بر اساس ایندکس

برای مرتب‌سازی با استفاده از محور، باید مشخص کنید که آیا می‌خواهید بر اساس ایندکس یا ستون مرتب‌سازی کنید. تنظیم پارامتر `axis` روی 0 نشان می‌دهد که می‌خواهید بر اساس ایندکس مرتب‌سازی کنید:

</div>

In [117]:
print(df.sort_index(axis=0, ascending=False, inplace=True))  # axis = 0 یعنی مرتب‌سازی بر اساس ایندکس

None

In [118]:
print(df)

                   A         B         C         D
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-05-30  0.070011 -0.516443 -1.655689  0.246721
2019-05-29  0.537438 -1.737568  0.714727 -0.939288
2019-05-28 -0.279572 -0.702492  0.252265  0.958977
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988
2019-05-25  0.187497  1.122150 -0.988277 -1.985934

<div dir="rtl">

**نکته:** توجه داشته باشید که تابع `sort_index()` دیتافریم مرتب شده را برمی‌گرداند. DataFrame اصلی تحت تأثیر قرار نمی‌گیرد. اگر می‌خواهید DataFrame اصلی مرتب شود، از پارامتر `inplace` استفاده کنید و آن را روی True تنظیم کنید. به طور کلی، اکثر عملیات مربوط به DataFrame، DataFrame اصلی را تغییر نمی‌دهند. بنابراین `inplace` به طور پیش‌فرض روی False تنظیم شده است. وقتی `inplace` روی True تنظیم شود، تابع None را به عنوان نتیجه برمی‌گرداند.

تنظیم پارامتر `axis` روی 1 نشان می‌دهد که می‌خواهید بر اساس برچسب‌های ستون مرتب‌سازی کنید:

</div>

In [119]:
print(df.sort_index(axis=1, ascending=False))  # axis = 1 یعنی مرتب‌سازی بر اساس ستون

                   D         C         B         A
2019-06-03 -0.030295 -0.945219  0.556775 -1.054974
2019-06-02  0.260466 -2.452653  1.706336  0.387023
2019-06-01  1.104195 -0.686285  0.856520 -0.185258
2019-05-31 -0.108726  2.107360  0.951517  0.001268
2019-05-30  0.246721 -1.655689 -0.516443  0.070011
2019-05-29 -0.939288  0.714727 -1.737568  0.537438
2019-05-28  0.958977  0.252265 -0.702492 -0.279572
2019-05-27  0.686223 -0.452978  0.067333 -0.040627
2019-05-26 -0.986988 -0.340693 -0.562243  0.360803
2019-05-25 -1.985934 -0.988277  1.122150  0.187497

<div dir="rtl">

### مرتب‌سازی بر اساس مقدار

برای مرتب‌سازی بر اساس مقدار، از تابع `sort_values()` استفاده کنید. دستور زیر DataFrame را بر اساس مقادیر ستون "A" مرتب می‌کند:

</div>

In [120]:
print(df.sort_values('B', axis=0))

                   A         B         C         D
2019-05-29  0.537438 -1.737568  0.714727 -0.939288
2019-05-28 -0.279572 -0.702492  0.252265  0.958977
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988
2019-05-30  0.070011 -0.516443 -1.655689  0.246721
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-06-02  0.387023  1.706336 -2.452653  0.260466

<div dir="rtl">

برای مرتب‌سازی بر اساس یک ایندکس خاص، پارامتر `axis` را روی 1 تنظیم کنید:

</div>

In [ ]:
print(df.sort_values('20190601', axis=1))

<div dir="rtl">

## اعمال توابع بر روی یک DataFrame

همچنین می‌توانید توابعی را بر روی مقادیر یک DataFrame با استفاده از تابع `apply()` اعمال کنید. ابتدا، بیایید دو تابع لامبدا را به صورت زیر تعریف کنیم:

</div>

In [163]:
import math
sq_root = lambda x: math.sqrt(x) if x > 0 else x
sq      = lambda x: x**2

<div dir="rtl">

تابع اول، `sq_root()`، ریشه دوم مقدار x را می‌گیرد اگر عدد مثبتی باشد. تابع دوم، `sq()`، مربع مقدار x را می‌گیرد.

توجه به این نکته مهم است که اشیاء ارسال شده به تابع `apply()` اشیاء Series هستند که ایندکس آنها یا ایندکس DataFrame (axis=0) یا ستون‌های DataFrame (axis=1) است.

اکنون می‌توانیم توابع را بر روی DataFrame اعمال کنیم. ابتدا، تابع `sq_root()` را بر روی ستون "B" اعمال کنید:

</div>

In [171]:
print(df.B)

0    1.856964
1    0.776567
2    0.231739
3    0.896598
4    0.234149
5   -0.869951
6    0.419996
7    0.707884
8   -0.024645
9    0.591121
Name: B, dtype: float64

In [169]:
print(df.B.apply(sq_root))

0    1.362705
1    0.881230
2    0.481393
3    0.946889
4    0.483890
5   -0.869951
6    0.648071
7    0.841359
8   -0.024645
9    0.768844
Name: B, dtype: float64

<div dir="rtl">

از آنجا که نتیجه `df.B` یک Series است، می‌توانیم تابع `sq_root()` را بر روی آن اعمال کنیم.

همچنین می‌توانید تابع `sq()` را بر روی `df.B` اعمال کنید:

</div>

In [172]:
print(df.B.apply(sq))

0    3.448316
1    0.603056
2    0.053703
3    0.803889
4    0.054826
5    0.756815
6    0.176396
7    0.501100
8    0.000607
9    0.349424
Name: B, dtype: float64

<div dir="rtl">

اگر تابع `sq_root()` را بر روی DataFrame به صورت زیر اعمال کنید:

</div>

In [174]:
translation = lambda x: x+7

In [175]:
df.apply(translation)    # ValueError

          A         B         C         D
0  6.818484  8.856964  7.402379  6.478585
1  6.190379  7.776567  6.535025  6.960974
2  7.853382  7.231739  6.483444  9.212415
3  7.423137  7.896598  6.663418  6.108608
4  8.794649  7.234149  5.153286  8.363579
5  5.935337  6.130049  7.270242  6.312976
6  6.618208  7.419996  8.972837  7.102781
7  5.971506  7.707884  7.298527  7.467032
8  6.435132  6.975355  6.795338  6.156562
9  6.357271  7.591121  6.756805  7.159419

<div dir="rtl">

خطا دریافت خواهید کرد. این به این دلیل است که شیء ارسال شده به تابع `apply()` در این مورد یک DataFrame است، نه یک Series. جالب اینجاست که می‌توانید تابع `sq()` را بر روی DataFrame اعمال کنید:

</div>

In [176]:
df.apply(sq)

          A         B         C         D
0  0.032948  3.448316  0.161909  0.271874
1  0.655487  0.603056  0.216202  0.001523
2  0.728261  0.053703  0.266830  4.894782
3  0.179045  0.803889  0.113287  0.794579
4  3.220764  0.054826  3.410353  1.859347
5  1.133507  0.756815  0.073031  0.472003
6  0.145765  0.176396  3.892087  0.010564
7  1.057800  0.501100  0.089118  0.218119
8  0.319076  0.000607  0.041887  0.711387
9  0.413101  0.349424  0.059144  0.025414

<div dir="rtl">

اگر می‌خواهید تابع `sq_root()` را بر روی کل DataFrame اعمال کنید، می‌توانید از طریق ستون‌ها تکرار کنید و تابع را بر روی هر ستون اعمال کنید:

</div>

In [177]:
for column in df:
    df[column] = df[column].apply(sq_root)
print(df)

          A         B         C         D
0 -0.181516  1.362705  0.634334 -0.521415
1 -0.809621  0.881230 -0.464975 -0.039026
2  0.923787  0.481393 -0.516556  1.487419
3  0.650490  0.946889 -0.336582 -0.891392
4  1.339645  0.483890 -1.846714  1.167724
5 -1.064663 -0.869951  0.519848 -0.687024
6 -0.381792  0.648071  1.404577  0.320595
7 -1.028494  0.841359  0.546376  0.683398
8 -0.564868 -0.024645 -0.204662 -0.843438
9 -0.642729  0.768844 -0.243195  0.399273

<div dir="rtl">

تابع `apply()` را می‌توان بر روی هر یک از محورها اعمال کرد: ایندکس (0؛ اعمال تابع بر روی هر ستون) یا ستون (1؛ اعمال تابع بر روی هر سطر). برای دو تابع لامبدای خاصی که تاکنون دیده‌ایم، فرقی نمی‌کند که آن را بر روی کدام محور اعمال کنید، و نتیجه یکسان خواهد بود. با این حال، برای برخی توابع، محوری که آن را بر روی آن اعمال می‌کنید مهم است. به عنوان مثال، دستور زیر از تابع `sum()` از NumPy استفاده می‌کند و آن را بر روی سطرهای DataFrame اعمال می‌کند:

</div>

In [178]:
print(df.apply(np.sum, axis=0))

A   -1.759761
B    5.519784
C   -0.507549
D    1.076113
dtype: float64

<div dir="rtl">

در اصل، شما تمام مقادیر را در هر ستون جمع می‌کنید.

اگر محور را روی 1 به صورت زیر تنظیم کنید:

</div>

In [179]:
print(df.apply(np.sum, axis=1))

0    1.294108
1   -0.432392
2    2.376043
3    0.369405
4    1.144545
5   -2.101790
6    1.991451
7    1.042638
8   -1.637613
9    0.282193
dtype: float64

<div dir="rtl">

## افزودن و حذف سطرها و ستون‌ها در یک DataFrame

تاکنون، تمام بخش‌های قبلی شامل استخراج سطرها و ستون‌ها از DataFrame و همچنین نحوه مرتب‌سازی DataFrame بوده است. در این بخش، بر روی نحوه افزودن و حذف ستون‌ها در DataFrame تمرکز خواهیم کرد.

قطعه کد زیر را در نظر بگیرید، جایی که یک DataFrame از یک دیکشنری ایجاد می‌شود:

</div>

In [199]:
import pandas as pd

data = {'name': ['Janet', 'Nad', 'Timothy', 'June', 'Amy'],
        'year': [2012, 2012, 2013, 2014, 2014],
        'reports': [6, 13, 14, 1, 7]}

df = pd.DataFrame(data, index =
       ['Singapore', 'China', 'Japan', 'Sweden', 'Norway'])
print(df)

              name  year  reports
Singapore    Janet  2012        6
China          Nad  2012       13
Japan      Timothy  2013       14
Sweden        June  2014        1
Norway         Amy  2014        7

<div dir="rtl">

### افزودن یک ستون

قطعه کد زیر نحوه افزودن یک ستون جدید به نام "school" به DataFrame را نشان می‌دهد:

</div>

In [202]:
import numpy as np

schools = np.array(["Cambridge","Oxford","Oxford","Cambridge","Oxford"])
df["school"] = schools
print(df)

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

<div dir="rtl">

### حذف سطرها

برای حذف یک یا چند سطر، از تابع `drop()` استفاده کنید. قطعه کد زیر دو سطری را که مقدار ایندکس آنها "China" و "Japan" است حذف می‌کند:

</div>

In [203]:
print(df.drop(['China', 'Japan']))  # حذف سطرها بر اساس مقدار ایندکس

            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford

In [204]:
print(df)

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

<div dir="rtl">

**نکته:** مانند تابع `sort_index()`، به طور پیش‌فرض تابع `drop()` دیتافریم اصلی را تحت تأثیر قرار نمی‌دهد. اگر می‌خواهید DataFrame اصلی را تغییر دهید، از پارامتر `inplace` استفاده کنید.

اگر می‌خواهید یک سطر را بر اساس یک مقدار ستون خاص حذف کنید، نام ستون و شرط را به این صورت مشخص کنید:

</div>

In [205]:
print(df[df.name != 'Nad'])         # حذف سطر بر اساس مقدار ستون

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

<div dir="rtl">

همچنین می‌توانید سطرها را بر اساس شماره سطر حذف کنید:

</div>

In [206]:
print(df.drop(df.index[1]))
# معادل df.drop['China']

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

<div dir="rtl">

اگر می‌خواهید چندین سطر را حذف کنید، شماره سطرها را به صورت یک لیست مشخص کنید:

</div>

In [207]:
print(df.drop(df.index[[1,2]]))     # حذف سطر دوم و سوم

            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford

<div dir="rtl">

دستور زیر سطر دوم از آخر را حذف می‌کند:

</div>

In [209]:
print(df)

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

In [210]:
print(df.drop(df.index[-2]))        # حذف سطر ماقبل آخر

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Norway         Amy  2014        7     Oxford

<div dir="rtl">

### حذف ستون‌ها

تابع `drop()` به طور پیش‌فرض سطرها را حذف می‌کند، اما اگر می‌خواهید به جای آن ستون‌ها را حذف کنید، پارامتر `axis` را روی 1 تنظیم کنید:

</div>

In [211]:
print(df.drop('reports', axis=1))   # حذف ستون

              name  year     school
Singapore    Janet  2012  Cambridge
China          Nad  2012     Oxford
Japan      Timothy  2013     Oxford
Sweden        June  2014  Cambridge
Norway         Amy  2014     Oxford

<div dir="rtl">

اگر می‌خواهید بر اساس شماره ستون حذف کنید، شماره ستون را با استفاده از ایندکسر `columns` مشخص کنید:

</div>

In [213]:
print(df)

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford

In [214]:
print(df.drop(df.columns[1], axis=1))       # حذف با استفاده از شماره ستون

              name  reports     school
Singapore    Janet        6  Cambridge
China          Nad       13     Oxford
Japan      Timothy       14     Oxford
Sweden        June        1  Cambridge
Norway         Amy        7     Oxford

<div dir="rtl">

همچنین می‌توانید چندین ستون را حذف کنید:

</div>

In [215]:
print(df.drop(df.columns[[1,3]], axis=1))   # حذف چندین ستون

              name  reports
Singapore    Janet        6
China          Nad       13
Japan      Timothy       14
Sweden        June        1
Norway         Amy        7

<div dir="rtl">

### ایجاد جدول تقاطعی (Crosstab)

در آمار، از جدول تقاطعی برای تجمیع و نمایش مشترک توزیع دو یا چند متغیر استفاده می‌شود. این جدول روابط بین این متغیرها را نشان می‌دهد. مثال زیر را در نظر بگیرید:

</div>

In [216]:
df = pd.DataFrame(
    {
        "Gender": ['Male','Male','Female','Female','Female'],
        "Team"  : [1,2,3,3,1]
    })
print(df)

   Gender  Team
0    Male     1
1    Male     2
2  Female     3
3  Female     3
4  Female     1

<div dir="rtl">

در اینجا شما یک DataFrame را با استفاده از یک دیکشنری ایجاد می‌کنید. وقتی DataFrame چاپ شود، خروجی زیر را خواهید دید. این DataFrame جنسیت هر فرد و تیمی را که فرد به آن تعلق دارد نشان می‌دهد. با استفاده از جدول تقاطعی، می‌توانید داده‌ها را خلاصه کنید و جدولی برای نمایش توزیع هر جنسیت برای هر تیم تولید کنید. برای انجام این کار، از تابع `crosstab()` استفاده کنید:

</div>

In [217]:
print("Displaying the distribution of genders in each team")
print(pd.crosstab(df.Gender, df.Team))

Displaying the distribution of genders in each team
Team    1  2  3
Gender
Female  1  0  2
Male    1  1  0

<div dir="rtl">

اگر می‌خواهید توزیع هر تیم را برای هر جنسیت ببینید، به سادگی آرگومان‌ها را معکوس کنید:

</div>

In [218]:
print(pd.crosstab(df.Team, df.Gender))

Gender  Female  Male
Team
1            1     1
2            0     1
3            2     0

<div dir="rtl">

## خلاصه

در این فصل، استفاده از Pandas برای نمایش داده‌های جدولی را مشاهده کردید. با دو ساختار داده اصلی Pandas آشنا شدید: Series و DataFrame. سعی کردم موارد را ساده نگه دارم و برخی از رایج‌ترین عملیات‌هایی را که می‌توانید بر روی این ساختارهای داده انجام دهید به شما نشان دهم. از آنجا که استخراج سطرها و ستون‌ها از DataFrame بسیار رایج است، برخی از این عملیات‌ها را در جدول زیر خلاصه کرده‌ام:

| شرح | نمونه کد |
|------|-----------|
| استخراج یک محدوده از سطرها با استفاده از شماره سطر | `df[2:4]` یا `df.iloc[2:4]` |
| استخراج یک سطر با استفاده از شماره سطر | `df.iloc[2]` |
| استخراج یک محدوده از سطرها و یک محدوده از ستون‌ها | `df.iloc[2:4, 1:4]` |
| استخراج یک محدوده از سطرها و ستون‌های خاص با استفاده از مقادیر موقعیت | `df.iloc[2:4, [1,3]]` |
| استخراج سطر(ها) و ستون(های) خاص | `df.iloc[[2,4], [1,3]]` |
| استخراج یک محدوده از سطرها با استفاده از برچسب‌ها | `df['20190601':'20190603']` |
| استخراج یک سطر بر اساس برچسب آن | `df.loc['20190601']` |
| استخراج سطر(های) خاص با استفاده از برچسب‌های آنها | `df.loc[[date1,date2]]` |
| استخراج سطر(های) و ستون(های) خاص با استفاده از برچسب‌های آنها | `df.loc[[date1,date2], ['A','C']]` یا `df.loc[[date1,date2], 'A':'C']` |
| استخراج یک محدوده از سطرها و ستون‌ها با استفاده از برچسب‌های آنها | `df.loc[date1:date2, 'A':'C']` |

</div>